language: python
python:
- "2.7"
install: "pip install -r requirements.txt"
before_script:
- autopep8 -ir *
- flake8 --max-complexity=10 --exclude=*.txt,*.md --max-line-length=200 *
script:
- cd Structured
- lettuce AceptanceTest
- cd UnitTest
- python Test_Triangule.py
- coverage run --branch Test_Triangle.py
- coverage report -m
- cd ../Traditional
- lettuce AceptanceTest
- cd UnitTest
- python Test_Triangule.py
- coverage run --branch Test_Triangle.py
- coverage report -m
